menu_main:
    #Jobs: /jobs
    #Archive: /archives/
    "2017 conference": https://2017.aifrontiers.com/
    "Videos": https://goo.gl/XvQs2S
    "Slides": https://goo.gl/CRzo7W
    #Rss: /atom.xml

menu_sub:
    "About": /about
    "Contact Us": /contact
    #Rss: /atom.xml

favicon: /images/favicon.png
logo: /images/logo.png

# Comment
# disqus:
# duoshuo:

# Google Analytics:
ga: UA-88635436-2

# Copyright Infomation
startyear: 2016

# Quote for subscribe
quote: Join our mailing list to hear updates

slogan: Watch speeches from our previous conference.
