menu:
    Blog: /
    #Archive: /archives/
    2017: https://www.aifrontiers.com/2017
    #Rss: /atom.xml

favicon: /images/favicon.png
logo: /images/logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016

# Quote for admonition
quote: AI Frontiers is the best AI conference in the world.
