menu_main:
    #Jobs: /jobs
    #Archive: /archives/
    "2017 conference": https://www.aifrontiers.com/2017
    Videos: https://www.youtube.com/playlist?list=PLnESksJKWdhg4EDJOjvqAizhgz3XCnCuU
    Slides: https://www.slideshare.net/AIFrontiers/presentations
    #Rss: /atom.xml

menu_sub:
    "About": /about
    "Contact Us": /contact
    #Rss: /atom.xml

favicon: /images/favicon.png
logo: /images/logo.png

# Comment
# disqus:
# duoshuo:

# Google Analytics:
ga: UA-88635436-2

# Copyright Infomation
startyear: 2016

# Quote for subscribe
quote: Join our mailing list to hear updates

slogan: Watch speeches from our previous conference.
