menu_main:
    #Jobs: /jobs
    #Archive: /archives/
    "2017 conference": https://www.aifrontiers.com/2017
    Videos: https://www.youtube.com/playlist?list=PLnESksJKWdhg4EDJOjvqAizhgz3XCnCuU
    Slides: https://www.slideshare.net/AIFrontiers/presentations
    #Rss: /atom.xml

menu_sub:
    "About us": /about-us
    "Contact us": /contact-us
    #Rss: /atom.xml

favicon: /images/favicon.png
logo: /images/logo.png

# Comment
disqus:
duoshuo:

# Analytics
# google-analytics:
#ga:

# Copyright Infomation
startyear: 2016

# Quote for admonition
quote: Join our mailing list to hear updates
slogan: Watch speeches from our previous conference.
